name: Backend CD

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: self-hosted
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Dockerfile exists
        run: |
          if [ ! -f /home/ubuntu/chat-app/backend/_work/chat_app_backend/chat_app_backend/Dockerfile ]; then
            echo "ERROR: Dockerfile not found!"
            exit 1
          fi
          echo "Dockerfile found ✓"

      - name: Stop Backend Container
        run: |
          cd /home/ubuntu/chat-app
          docker-compose stop backend || true
          docker rm -f chat-app_backend_1 || true

      - name: Clean Docker State
        run: |
          docker container prune -f
          docker image prune -f
          docker rmi chat-app_backend || true

      - name: Build Backend
        run: |
          cd /home/ubuntu/chat-app
          docker-compose build --no-cache backend

      - name: Deploy Backend
        run: |
          cd /home/ubuntu/chat-app
          docker-compose up -d backend

      - name: Verify Deployment
        run: |
          sleep 10
          docker ps | grep backend
          docker logs $(docker ps -q -f name=backend) --tail 50
