name: Backend CD

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Dockerfile exists
        run: |
          if [ ! -f /home/ubuntu/chat-app/backend/_work/backend/backend/Dockerfile ]; then
            echo "ERROR: Dockerfile not found!"
            exit 1
          fi
          echo "Dockerfile found ✓"

      - name: Stop and Clean Old Containers
        run: |
          cd /home/ubuntu/chat-app
          docker-compose down backend || true
          docker image prune -f

      - name: Build and Deploy backend
        run: |
          cd /home/ubuntu/chat-app
          docker-compose build --no-cache backend
          docker-compose up -d backend
