name: Backend CD

on:
  workflow_run:
    workflows: ["Backend CI"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 15
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Ensure Network Exists
        run: docker network create chat-app_default 2>/dev/null || true

      - name: Stop and Remove Old Backend
        run: |
          docker stop chat-app_backend_1 2>/dev/null || true
          docker rm -f chat-app_backend_1 2>/dev/null || true
          docker rmi -f chat-app_backend 2>/dev/null || true

      - name: Build Backend
        run: |
          cd /home/ubuntu/chat-app
          docker-compose build --no-cache backend

      - name: Ensure Mongo Running
        run: |
          if ! docker ps | grep -q chat-app_mongo_1; then
            docker run -d \
              --name chat-app_mongo_1 \
              --network chat-app_default \
              -p 8080:27017 \
              --restart unless-stopped \
              mongo
            sleep 5
          fi

      - name: Deploy Backend
        run: |
          docker run -d \
            --name chat-app_backend_1 \
            --network chat-app_default \
            -p 4000:4000 \
            --env-file /home/ubuntu/chat-app/backend/.env.prod \
            --restart unless-stopped \
            chat-app_backend

      - name: Verify Deployment
        run: |
          sleep 10
          docker ps | grep backend
          docker logs chat-app_backend_1 --tail 50
