name: Backend CI

on:
  push:
    branches: [main]

jobs:
  build-backend:
    runs-on: self-hosted

    steps:
      - name: Checkout Backend
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Build Docker Images
        run: docker build -t backend:latest ./backend
